version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Optional: Add a database service for demo
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: demo
  #     POSTGRES_USER: demo
  #     POSTGRES_PASSWORD: demo
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: 