[build]
  # Build command for Netlify
  command = "npm run build:netlify"
  
  # Publish directory (where the built files will be)
  publish = "dist"
  
  # Functions directory for serverless functions
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Environment variables
  NODE_ENV = "production"
  SITE_NAME = "demoforteamcity"

# Site configuration
[context.production.environment]
  SITE_NAME = "demoforteamcity"
  SITE_ID = "492d1086-0844-46ed-9b2c-b61b7d1cf513"

# Redirects for SPA and API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 