[build]
  # What to run when building the site
  command = "npm run build:netlify"
  
  # Where to find the files to serve
  publish = "dist"
  
  # Where our serverless functions live
  functions = "netlify/functions"

[build.environment]
  # Use Node.js 18
  NODE_VERSION = "18"
  
  # Set up the environment
  NODE_ENV = "production"
  SITE_NAME = "demoforteamcity"

# Production environment settings
[context.production.environment]
  SITE_NAME = "demoforteamcity"
  SITE_ID = "492d1086-0844-46ed-9b2c-b61b7d1cf513"

# Set up redirects for the single-page app and API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add some security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 